### ISSUE TITLE
does GITHUB_TOKEN work to get around rate limiting

### ISSUE THREAD

**Issue by mattm-ecoatm** [minamijoyo/tfupdate#131]
All of the sudden I started to run into a bunch of rate limiting issues with Github. I tried to set the env GITHUB_TOKEN, but it still seems like i still get 404s. Is there a way to use a token when trying generate the lock file?

**Comment by minamijoyo** [comment]
I have not observed any rate limits in my environment so far. What commands do you run, and which API rate limits are caught?

**Comment by mattm-ecoatm** [comment]
I use tfupdate in precommit and have a few tasks to update a few providers and the lock file.

Basically it's a rate limit to the GitHub api. I can try to reproduce it again, but I wasn't able to update the lock file since by that time I kept getting rate limited.

This hasn't really happened to me before, not sure if GitHub has made changes to how they rate limit or what.

**Comment by minamijoyo** [comment]
I am not using tfupdate on the pre-commit hook; I am using it on CI/CD.
If you can clarify the reproduction conditions, I can help a bit more.

**Comment by mattm-ecoatm** [comment]
My pre-commit looks something like this:

```
- name: tfupdate terraform
  id: tfupdate
  args:
    - --args=terraform
    - --args=--version="~> 1.9"

- name: tfupdate DataDog/datadog
  id: tfupdate
  args:
    - --args=provider DataDog/datadog

- name: tfupdate hashicorp/aws
  id: tfupdate
  args:
    - --args=provider hashicorp/aws

- name: tfupdate lock
  id: tfupdate
  args:
    - --args=lock
    - --args=--platform=linux_amd64
    - --args=--platform=darwin_amd64
    - --args=--platform=darwin_arm64
```

I just run `pre-commit run --all-files` a few times and run into something like this:

> failed to list releases for hashicorp/terraform-provider-aws: GET https://api.github.com/repos/hashicorp/terraform-provider-aws/releases?per_page=100: 403 API rate limit exceeded for xxxxxxxxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 59m32s]

If i go to the browser I get the same message with a link to the docs:

> "message":"API rate limit exceeded for xxxxxxxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

But then based on this documentation https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28, it basically just says use a token to increase the limit. So thats why I was wondering if I could somehow use a token.

The tfupdate lock command just silently fails. If i run the terraform command directly `terraform providers lock -platform=linux_amd64 -platform=darwin_amd64 -platform=darwin_arm64`, then its ok, but obviously slow.

When running within CI/CD using github actions, it seems to be ok and I haven't run into this issue there, only on my computer.
